//
//  RecipeServiceTests.swift
//  RecipleaseTests
//
//  Created by RaphaÃ«l Payet on 18/06/2021.
//

import XCTest
@testable import Reciplease

class RecipeServiceTests: XCTestCase {

    func testGivenCallbackFailed_WhenErrorInNetworkCall_ThenObjectReturnAreNil(){
//        // MARK: - Given
//
//        // I want to create a fake request
//        let fakeRequest = FakeNetworkRequest()
//
//        // I want to pass the request to the fake session of Alamofire
//        let fakeSession = FakeAFSession(request: fakeRequest)
//
//        // Finally, I want to pass the session to the service
//        let service = RecipeService(session: fakeSession)
//
//        // MARK: - When
//        let expectation = XCTestExpectation(description: "Error in network call")
//
//        let fakeIngredients = ["Mozzarella", "Tomato"]
//        service.getRecipe(containing: fakeIngredients) { _recipes, success, _error in
//            // MARK: - Then
//            // Here is where I should test the network call
//
//            XCTAssertNil(_recipes)
//            XCTAssertFalse(success)
//            XCTAssertNotNil(_error)
//
//        }
//        wait(for: [expectation], timeout: 0.01)
    }
    
}
